### ISSUE TITLE
apkmirror.com

### ISSUE THREAD

**Issue by exodius48** [reek/anti-adblock-killer#1083]
http://www.apkmirror.com/apk/klinker-apps/evolvesms/evolvesms-4-2-0-release/evolvesms-4-2-0-android-apk-download/
http://i.imgur.com/JjMhYgM.png
Firefox 44.0.2
Greasemonkey
uBlock Origin
AAK, EasyList,  Adblock Warning Removal List‎, Spam404, Fanboy’s Social Blocking List‎, etc

**Comment by reek** [comment]
Hi,
Its killed for me.

**Comment by exodius48** [comment]
I already updated AAK to 9.2 & updated AAK script inside uBlock Origin, still get message to disable adblocker like image above.

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by maynak00** [comment]
I have the same problem in chromium.I fixed with block inline-script.but not recommended for everyone(may broke site functionality or usability).but for me, no problem with: ||apkmirror.com$inline-script

**Comment by reek** [comment]
@maynak00 
this is not a good idea.

**Comment by reek** [comment]
@exodius48 
Can you test this version 
https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by reek** [comment]
@maynak00 
You should rather use this filter.
<code>apkmirror.com##script:contains(canRunAds = false)</code>

**Comment by exodius48** [comment]
@reek i already wrote as guidelines. btw, i have tested it, but still get countdown timer to disable ads.

**Comment by reek** [comment]
@exodius48 
No, guideline advanced

**Comment by exodius48** [comment]
Source Code: http://paste2.org/CEWtUEK3
Extensions: uBlock Origin, Greasemonkey, IDM integration, Multifox, ImageBlock, UserAgent Switcher
Userscripts: Anti-Adblock Killer, AntiAdware, Adsbypasser, 
Blocked Resources: http://i.imgur.com/opTXWW9.png Full Logs: http://paste2.org/nNtLgMZ9

@reek Done bro.

**Comment by reek** [comment]
@exodius48 
Try just uBlock filters, EasyList, AakList, EasyPrivacy 
or 
add rule <code>apkmirror.com##script:contains(canRunAds = false)</code>
or
https://github.com/reek/anti-adblock-killer#help

**Comment by exodius48** [comment]
@reek naah..its working now. (y)
apkmirror killed.

**Comment by reek** [comment]
@exodius48 
Ok :smile:, but this rule only works with FF and uBo.

**Comment by exodius48** [comment]
@reek Its ok, ublock is better for me. :D 
would you update reek script / AAK to latest version in order to support apkmirror?

**Comment by reek** [comment]
@exodius48 
Yes

**Comment by maynak00** [comment]
@reek, tested this with chromium x64+uBlock Origin: apkmirror.com##script:contains(canRunAds = false)
but not working(with Chromium).do you have a solution for chromium+ublock origin+tampermonkey ?(I have firefox too.but chromium works faster for my old pc.using firefox for unity webplayer support and NPAPI)

**Comment by exodius48** [comment]
@maynak00 same with me, but not a big problem because im using firefox, chrome just for download apk from play store.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
@maynak00 
For the moment you must use FF and uBO.
