### ISSUE TITLE
Anti Adblock Killer not working on KissAnime.ru

### ISSUE THREAD

**Issue by joshuam1008** [reek/anti-adblock-killer#4396]
kissanime.ru
https://imgur.com/2tthiNv
Google Chrome Version 83.0.4093.3 (Official Build) dev (64-bit)
uBlock Origin
Tampermonkey
EasyList + Peter Lowe’s Ad and tracking server list + https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

When adblocker is disabled, the site works normally (but glitchy because there are so many ads). As seen in the screenshot, while the website does not initially detect the adblocker, videos fail to load. In the screenshot provided, I was using ProtonVPN. When I was not using a VPN, not only did the video fail to load but I was brought to the "Access Denied" page and my IP was banned. I've heard there has been a little jump in people with Adblockers getting banned. I believe they have updated their anti adblocker again.

**Comment by liamengland1** [comment]
Uninstall anti-adblock-killer, it has been abandoned for 2 years. Update your uBlock origin filterlists, the issue is fixed.

**Comment by joshuam1008** [comment]
> Uninstall anti-adblock-killer, it has been abandoned for 2 years. Update your uBlock origin filterlists, the issue is fixed.

I have auto-update filter lists. I'm pretty sure my uBlock and its lists are all up to date. How would uBlock Origin alone bypass an anti-adblocker? I apologize if I am misunderstanding something. Thanks

**Comment by liamengland1** [comment]
For a long time now uBlock Origin has implemented scriptlets (https://github.com/gorhill/uBlock/wiki/Resources-Library), meaning that even the most advanced anti-adblock can be dealt with.

**Comment by liamengland1** [comment]
Also add this to your custom filters and see if it helps: `kissanime.*##+js(acis, AddCloseButton)`

**Comment by joshuam1008** [comment]
> Also add this to your custom filters and see if it helps: `kissanime.*##+js(acis, AddCloseButton)`

I'm not getting banned yet but videos are still failing to load unless uBlock origin is disabled. Thank you though! I'll do some more troubleshooting on my own

**Comment by liamengland1** [comment]
Does the anti-adblock you are seeing look like this:
![image](https://user-images.githubusercontent.com/16567977/77862337-c33b0d80-71e8-11ea-8cc8-709884e82642.png)

**Comment by joshuam1008** [comment]
Unfortunately no, it still looks exactly like my initial screenshot, even with AAK disabled. uBlock Origin appears to be doing something (or KissAnime) that prevents the video from loading at all. I have a temporary workaround: I can still download the video. I just can't use the in-browser player.

**Comment by liamengland1** [comment]
Try another server?

**Comment by joshuam1008** [comment]
I tried all servers. Still didn't work :(

Lol and I've made an existing problem even worse. Chrome + Mac seem to hate each other and me messing around with extensions caused Chrome Helper (Renderer) to start going crazy and use over 100% of CPU over and over and over. Quit that thing so many times. 

Thank you for your help though!

**Comment by liamengland1** [comment]
Well, since no anti-adblock message is showing, I think one of your other extensions might be interfering with the site.
