### ISSUE TITLE
openload (network)

### ISSUE THREAD

**Issue by maynak00** [reek/anti-adblock-killer#475]
archive:
https://openload.io/f/dV65XxYcdeI/mrrbts1e2.hd72_300mbfilms.com.rar
https://openload.co/f/dV65XxYcdeI/mrrbts1e2.hd72_300mbfilms.com.rar

video:
https://openload.co/f/L9K6t7ssO9U/Acquarius101.avi

http://i.imgbox.com/yNSq3XLq.png
Chromium x64
Tampermonkey BETA+ https://greasyfork.org/scripts/4881-adsbypasser/ https://greasyfork.org/scripts/735-anti-adblock-killer-reek/ https://greasyfork.org/scripts/4294-antiadware/
uBlock Origin
Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy (adblockplus.org)‎, Adblock Warning Removal List‎
**EDIT:** caused by EasyList 
Static filter /markpop.js found in:EasyList
Static filter @@||openload.io^$elemhide found in:EasyList
I blocked ||onclickads.net^
from your script @@||openload.io/assets/js/pop.js$script
solution: @@||openload.io/assets/js/markpop.js$script
if I add last line.popup come and gone immediately.can you block automatic popup?

**Comment by MajkiIT** [comment]
For me, solution is:
@@|https://openload.io/assets/js/adconfig.js$script,domain=openload.io

**Comment by maynak00** [comment]
tested with ublock origin.not working for me.
fixed with permanent rule ublock origin openload.io openload.io * allow
ads gone but popups come and gone instantly.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by maynak00** [comment]
tested on chrome stable."The publisher of this file doesnt allow adblock, please disable and reload !".please fix.
Chrome 44.0.2403.130 m (64-bit)
>https://openload.tv/adblock.js
>https://openload.io/assets/js/adblockad.js

with ublock origin. **openload.io openload.tv * allow**
fixing issue temporarily

**Comment by reek** [comment]
Ok, thanks

**Comment by maynak00** [comment]
please try or add:
>@@openload.tv/adconfig.js
not need"with ublock origin. **openload.io openload.tv * allow**"

optional(not for adblocking):
>||https://openload.co/$xmlhttprequest

**Comment by JurajNyiri** [comment]
Add to filters:

`@@openload.tv/adconfig.js`
`@@openload.co/adconfig.js`

Fixed.

**Comment by reek** [comment]
it will be done, thanks

**Comment by JurajNyiri** [comment]
@reek 
Script on openload has been updated, now it detects adblock somehow differently, i have enabled everything in filters and it has still detected adblock.

**Comment by JurajNyiri** [comment]
My solution for openload: https://github.com/JurajNyiri/OLEnhancedPlayer

**Comment by reek** [comment]
@JurajNyiri 
ok, but I just tested it with firefox video link http://tinyurl.com/qdycrgz. and I still have the anti-adblock message

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by JurajNyiri** [comment]
@reek 

Its still not working with the newest update of your script.

However, I got it working with my script and its new update. They responded pretty fast to my script so hopefully this will take them longer. I have also fixed some stuff and added new features.

It works best on embeded videos from openload, but also now works on the main page, for example, your link.

Link: https://github.com/JurajNyiri/OLEnhancedPlayer

**Comment by reek** [comment]
@JurajNyiri 
its ok now, but Pause/Play with spacebar or click anywhere.dont works

**Comment by maynak00** [comment]
tested with video and rar link.but still adblocker detected message.
temporary solution wtih ublock origin: openload.co openload.co * allow

https://openload.co/assets/css/style.css has some .adblock content.but not working with allow/do not block filter:
@@openload.co/assets/css/style.css
@@openload.tv/assets/css/style.css

I also blocked with ublock origin(no popups)
openload.co popads.net * block
openload.co bootstrapcdn.com * block
openload.co padstm.com * block

**Comment by reek** [comment]
@maynak00 
update AakList, tested ok on Chrome + uBlock

**Comment by maynak00** [comment]
@reek 
thanks.fixed with update(chromium+ublock origin).no need ublock origin Permanent rule.

**Comment by SMed79** [comment]
Hi, 
nor work for me on `http://www.mangas-vostfr.com/one-piece-episode-de-sabo-vostfr/`

![openload.co](https://cloud.githubusercontent.com/assets/1873139/9794296/3a0b7f6a-57e2-11e5-94ae-583bf46c4b69.png)

**Comment by reek** [comment]
@SMed79 
No message detected, try update AakList

**Comment by maynak00** [comment]
@reek, not about antiadblock. openload opens different popups when I first click "Free Download".
I can't block with ||openload.co^$popup
sometimes popups blocked sometimes not
can you help?
ad/popup sources:
http://eclkmpsa.com/adServe/banners?tid=OPLOIODL&action=r
http://www.blkget8.com/?tp=iw&cid=5062&v=4&clickid=012500239027377311422&a=1&cachecode=dyNllQGLFdOvNOTokKOVOQ
http://www.musixhub.com/wim/lp/lp4/index_87.php?rh=1&cid=5062&v=4&clickid=012500239027377311422&a=1&cachecode=dyNllQGLFdOvNOTokKOVOQ&rd=78

maybe problem with this filter in EasyList: @@||openload.co^$script
not blocked:
https://openload.co/assets/8c30b265/yii.activeForm.js
https://openload.co/assets/8c30b265/yii.validation.js
https://openload.co/assets/8c30b265/yii.js
https://openload.co/assets/js/bootstrap.min.js
https://openload.co/assets/js/jquery-select-list.js
https://openload.co/assets/js/jquery.jtruncate.pack.js
https://openload.co/assets/js/advertisement.js

**Comment by SMed79** [comment]
@maynak00 look like [adware](https://en.wikipedia.org/wiki/Adware)/[unwanted program](https://en.wikipedia.org/wiki/Potentially_unwanted_program) infection & [Adblock Plus](https://adblockplus.org/) can not block this type of ad.

This is how to remove: https://forums.lanik.us/viewtopic.php?f=62&t=25052#p76584, if not resolved, you can seek assistance on specialized forums such as http://ccm.net/forum/viruses-security-7.

**Comment by maynak00** [comment]
@SMed79 thank you for suggestions.
browser not infected.no problem with another web sites(including youtube).only on openload. 
URLs grabbed with ublock origin network logger chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/logger-ui.html
my extensions usually disabled.I have/enabled ublock origin,tampermonkey beta,session buddy,extensions manager(aka switcher),VkOpt,Empty New Tab Page,Disable YouTube HTML5 Player,IDM Integration Module, Link2Clip,umatrix(sometimes)
sometimes I check computer with adwcleaner,malwarebytes antimalware,superantispyware
unchecky and winpatrol running in background.I also checking processes always with Process Hacker
no VPN or proxy.UAC disabled.autorun completely disabled.I don't need antivirus.no problem in c:\windows\system32\drivers\etc\hosts file.ads not injected(like deals) every page.search engine not changed.no search engine redirections to wrong pages.homepage not changed(empty about:blank),no toolbars.no click tracking

**Comment by SMed79** [comment]
@maynak00 using [Adblock plus](http://adblockplus.org/) (firefox) please submit an **[issue repport](https://adblockplus.org/getting_started#false-negatives)** and paste the link here !

you English is good i am using google translate :)

**Comment by maynak00** [comment]
@SMed79 ad blocked with adblock plus(chromium).also today blocked with ublock origin(chromium).
I can't report issue in ublock origin with EasyList filter
Can I report here? (uBlock Origin + EasyList): https://forums.lanik.us/viewforum.php?f=62
Static Filter in EasyList helped(thanks): |http:$domain=allmyvideos.net|embed.videoweed.es|extreme-board.com|filepost.com|filmovizija.com|go4up.com|imagebam.com|imageporter.com|imgbox.com|imgmade.com|imgspice.com|load.to|mofunzone.com|openload.co|putlocker.is|thevideo.me|twer.info|vidspot.net|watchcartoononline.com|xtshare.com|youwatch.org,third-party,popup

@reek, this blocked with EasyList and adblocker detected message(The publisher of this file doesnt allow adblock, please disable and reload !): https://openload.co/Adv.png
I added to custom filters: @@||https://openload.co/Adv.png

**Comment by SMed79** [comment]
* `Can I report here?`

Yes you can report on https://forums.lanik.us/viewforum.php?f=62 (Registration not required).

* `Static Filter in EasyList helped`

|http:$subdocument,third-party,popup,domain=allmyvideos.net|embed.videoweed.es|extreme-board.com|filepost.com|filmovizija.com|go4up.com|imagebam.com|imageporter.com|imgbox.com|imgmade.com|imgspice.com|load.to|mofunzone.com|openload.co|putlocker.is|thevideo.me|twer.info|vidspot.net|watchcartoononline.com|xtshare.com|youwatch.org

* `I added to custom filters`

@@||openload.co/Adv.png$image

**Comment by maynak00** [comment]
@reek adblocker detected again.can you check?.
"The publisher of this file doesnt allow adblock, please disable and reload !"
maybe problem with website.because disabled ublock origin and tampermonkey.still adblocker detected message.

**Comment by maynak00** [comment]
@reek adblocker detected again.can you check?.
"The publisher of this file doesnt allow adblock, please disable and reload !"

**Comment by reek** [comment]
@maynak00 
Ok, thanks, i will add rule

**Comment by maynak00** [comment]
@reek adblocker detected again.can you check?.
"The publisher of this file doesnt allow adblock, please disable and reload !"

problem with Easylist (Static filter /advertisement.css)
problem solved with custom filter:
>@@/advertisement.css$domain=~example.com,stylesheet
similar to your filter @@/advertisement.js$domain=~example.com,script

**Comment by reek** [comment]
@maynak00
Ok, thanks, i will add rule

**Comment by MajkiIT** [comment]
@reek 
I wrote it https://github.com/reek/anti-adblock-killer/issues/840

**Comment by maynak00** [comment]
@reek adblocker detected again.can you check?.
"The publisher of this file doesnt allow adblock, please disable and reload !"
problem with Easylist (Static filter .com/ad.$domain=~ad-tuning.de)
**new filter:**
>@@/ad*.js$domain=~example.com,script
or
>@@/ad.js$domain=~example.com,script

**Comment by reek** [comment]
@maynak00 
Ok, thanks, but I have already planned to fix it with AakSript

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
